version: 2
updates:
- package-ecosystem: npm
  directory: "/js"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: lodash
    versions:
    - 4.17.20
